# This file was generated by the {rix} R package v0.16.0 on 2025-05-13
# with following call:
# >rix(r_ver = "4.3.2",
#  > r_pkgs = c("DBI",
#  > "MASS",
#  > "Matrix",
#  > "R.methodsS3",
#  > "R.oo",
#  > "R.utils",
#  > "R6",
#  > "RColorBrewer",
#  > "Rcpp",
#  > "RcppArmadillo",
#  > "RcppParallel",
#  > "askpass",
#  > "assertthat",
#  > "babelwhale",
#  > "backports",
#  > "base64enc",
#  > "base64url",
#  > "bit",
#  > "bit64",
#  > "blob",
#  > "broom",
#  > "bslib",
#  > "cachem",
#  > "callr",
#  > "cellranger",
#  > "cli",
#  > "clipr",
#  > "codetools",
#  > "colorspace",
#  > "conflicted",
#  > "cpp11",
#  > "crayon",
#  > "curl",
#  > "data.table",
#  > "dbplyr",
#  > "desc",
#  > "digest",
#  > "dotenv",
#  > "dplyr",
#  > "dtplyr",
#  > "dynutils",
#  > "ellipsis",
#  > "evaluate",
#  > "fansi",
#  >  "farver",
#  > "fastmap",
#  > "fontawesome",
#  > "forcats",
#  > "fs",
#  > "future",
#  > "future.callr",
#  > "gargle",
#  > "generics",
#  > "ggplot2",
#  > "globals",
#  > "glue",
#  > "googledrive",
#  > "googlesheets4",
#  > "gtable",
#  > "haven",
#  > "highr",
#  > "hms",
#  > "htmltools",
#  > "htmlwidgets",
#  > "httr",
#  > "ids",
#  > "igraph",
#  > "isoband",
#  > "janitor",
#  > "jquerylib",
#  > "jsonlite",
#  > "knitr",
#  > "labeling",
#  > "lattice",
#  > "lifecycle",
#  > "listenv",
#  > "lubridate",
#  > "magrittr",
#  > "memoise",
#  > "mgcv",
#  > "mime",
#  > "modelr",
#  > "munsell",
#  > "nlme",
#  > "openssl",
#  > "parallelly",
#  > "pillar",
#  > "pkgconfig",
#  > "prettyunits",
#  > "processx",
#  >  "progress",
#  > "proxyC",
#  > "ps",
#  > "purrr",
#  > "ragg",
#  > "rappdirs",
#  > "readr",
#  > "readxl",
#  > "rematch",
#  > "rematch2",
#  > "remotes",
#  > "renv",
#  > "reprex",
#  > "rlang",
#  > "rmarkdown",
#  > "rstudioapi",
#  > "rvest",
#  > "sass",
#  > "scales",
#  > "selectr",
#  > "snakecase",
#  > "stringi",
#  > "stringr",
#  > "sys",
#  > "systemfonts",
#  > "tarchetypes",
#  > "targets",
#  > "textshaping",
#  > "tibble",
#  > "tidyr",
#  > "tidyselect",
#  > "tidyverse",
#  > "timechange",
#  > "tinytex",
#  > "tzdb",
#  > "utf8",
#  > "uuid",
#  > "vctrs",
#  > "viridisLite",
#  > "visNetwork",
#  > "vroom",
#  > "withr",
#  > "xfun",
#  > "xml2",
#  > "yaml"),
#  > git_pkgs = NULL,
#  > project_path = ".")
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2023-12-30.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      askpass
      assertthat
      babelwhale
      backports
      base64enc
      base64url
      bit
      bit64
      blob
      broom
      bslib
      cachem
      callr
      cellranger
      cli
      clipr
      codetools
      colorspace
      conflicted
      cpp11
      crayon
      curl
      data_table
      DBI
      dbplyr
      desc
      digest
      dotenv
      dplyr
      dtplyr
      dynutils
      ellipsis
      evaluate
      fansi
      farver
      fastmap
      fontawesome
      forcats
      fs
      future
      future_callr
      gargle
      generics
      ggplot2
      globals
      glue
      googledrive
      googlesheets4
      gtable
      haven
      highr
      hms
      htmltools
      htmlwidgets
      httr
      ids
      igraph
      isoband
      janitor
      jquerylib
      jsonlite
      knitr
      labeling
      lattice
      lifecycle
      listenv
      lubridate
      magrittr
      MASS
      Matrix
      memoise
      mgcv
      mime
      modelr
      munsell
      nlme
      openssl
      parallelly
      pillar
      pkgconfig
      prettyunits
      processx
      progress
      proxyC
      ps
      purrr
      R_methodsS3
      R_oo
      R_utils
      R6
      ragg
      rappdirs
      RColorBrewer
      Rcpp
      RcppArmadillo
      RcppParallel
      readr
      readxl
      rematch
      rematch2
      remotes
      renv
      reprex
      rlang
      rmarkdown
      rstudioapi
      rvest
      sass
      scales
      selectr
      snakecase
      stringi
      stringr
      sys
      systemfonts
      tarchetypes
      targets
      textshaping
      tibble
      tidyr
      tidyselect
      tidyverse
      timechange
      tinytex
      tzdb
      utf8
      uuid
      vctrs
      viridisLite
      visNetwork
      vroom
      withr
      xfun
      xml2
      yaml;
  };
     
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      glibcLocales
      nix
      R;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    buildInputs = [  rpkgs   system_packages   ];
    
  }; 
in
  {
    inherit pkgs shell;
  }
